[pytest]
minversion = 8.0
testpaths = tests
addopts = -ra --strict-markers
markers =
    slow: slow tests
    benchmark: benchmark tests
    integration: integration tests
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
